//
//  IO.Event.Registration.Reply.ID.swift
//  swift-io
//
//  Created by Coen ten Thije Boonkkamp on 29/12/2025.
//

extension IO.Event.Registration.Reply {
    /// Identifier for matching registration requests to replies.
    ///
    /// Generated by the selector using a monotonically increasing counter.
    /// Overflow wraps (wrapping add), which is safe for matching purposes.
    public typealias ID = Tagged<IO.Event.Registration.Reply, UInt64>
}
