//
//  IO.Event.Registration.Reply.swift
//  swift-io
//
//  Created by Coen ten Thije Boonkkamp on 29/12/2025.
//

extension IO.Event.Registration {
    /// A reply from the poll thread to the selector for a registration request.
    ///
    /// Replies are pushed by the poll thread via `Reply.Bridge` and processed
    /// by the selector actor. This ensures all continuations are resumed on
    /// the selector executor (single resumption funnel).
    public struct Reply: Sendable {
        /// The reply ID matching the original request.
        public let id: ReplyID

        /// The result of the registration operation.
        public let result: Result<Payload, IO.Event.Error>

        public init(id: ReplyID, result: Result<Payload, IO.Event.Error>) {
            self.id = id
            self.result = result
        }
    }

    /// Identifier for matching registration requests to replies.
    ///
    /// Generated by the selector using a monotonically increasing counter.
    /// Overflow wraps (wrapping add), which is safe for matching purposes.
    public typealias ReplyID = Tagged<Reply, UInt64>

    /// Payload of a successful registration reply.
    public enum Payload: Sendable, Equatable {
        /// Registration succeeded, returning the assigned ID.
        case registered(IO.Event.ID)

        /// Modification succeeded.
        case modified

        /// Deregistration succeeded.
        case deregistered
    }
}
